prompts:
  - "file://.prompts_cache/coder.txt"

providers:
  - id: openai:gpt-4o-mini

tests:
  - vars:
      request: "Write function to print 'Hello World' in Python."
    assert:
      - type: icontains
        value: "python"