FROM python:3.12-slim

ENV PYTHONPATH=/app \
    UV_PROJECT_ENVIRONMENT=/usr/local

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-install-project

WORKDIR /app

COPY . .

RUN uv sync --frozen

EXPOSE 8000

WORKDIR /app
CMD ["uvicorn", "unilm.main:app", "--host", "0.0.0.0", "--port", "8000"]